#!/usr/bin/env bash
set -euo pipefail

TARGET_DB="${POSTGRES_DB}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$TARGET_DB" <<SQL
REVOKE ALL ON DATABASE "$TARGET_DB" FROM PUBLIC;

CREATE ROLE app_migrator
  LOGIN
  PASSWORD '${APP_MIGRATOR_PASSWORD}'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE;

CREATE ROLE api_user
  LOGIN
  PASSWORD '${API_DB_PASSWORD}'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE;

CREATE ROLE worker_user
  LOGIN
  PASSWORD '${WORKER_DB_PASSWORD}'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE;

GRANT CONNECT ON DATABASE "$TARGET_DB" TO app_migrator, api_user, worker_user;

GRANT CREATE ON DATABASE personalwebsite TO app_migrator;

CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION app_migrator;

GRANT USAGE ON SCHEMA app TO api_user, worker_user;

ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA app
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_user, worker_user;

ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA app
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO api_user, worker_user;
SQL