import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by me on my lonesome"
}

export default function Home() {
	return (
		<div className="space-y-16">
			<section className="mt-16">
				<div className="max-w-6xl mx-auto px-4 flex flex-col md:flex-row">
					<div className="flex-1">
						<h1>About</h1>
						<p>I&apos;m James McDonald, a full-stack developer with a background in digital marketing.</p>
						<p className="px-4 mt-4">
							My work sits at the intersection of marketing, systems, and software. I&apos;m interested 
							in building practical tools that reduce repetitive work, improve visibility, and 
							make data more useful. This website is both my portfolio and a home for the 
							tools I&apos;m building.
						</p>
					</div>
					<div className="flex-1"></div>
				</div>
			</section>
			<section className="mt-16">
				<div className="max-w-6xl mx-auto px-4">
					<h2>Current work</h2>
					<div className="px-4 flex flex-col gap-4">
						<p>
							I currently work at <a href="https://www.exponential-e.com" className="link-styled" target="_blank" rel="noopener noreferrer">Exponential-e</a>, where I&apos;ve taken on broad responsibility across digital 
							marketing, reporting, lead flow, platform optimisation, and website-related problem solving.
						</p>
						<p>
							My work sits at the intersection of marketing, systems, and software. I&apos;m interested 
							in building practical tools that reduce repetitive work, improve visibility, and 
							make data more useful. This website is both my portfolio and a home for the 
							tools I&apos;m building.
						</p>
						<p>
							After my manager left in January 2025, I took on much greater day-to-day ownership during 
							a difficult period that included an economic downturn and analytics disruption caused by 
							server changes. Since then, I&apos;ve worked across budget management, campaign delivery, reporting, 
							lead handoff, platform improvements, and website troubleshooting.
						</p>
						<p>
							My work has included Google Ads, LinkedIn Ads, Qualified AI, campaign tracking, dashboarding, UTM 
							governance, and cross-functional support for digital campaigns. During my time there, I reduced 
							low-quality Google Ads leads from a peak of around 60% to 8%, took ownership of a six-figure budget, 
							and helped influence eight figures of Total Contract Value pipeline through web and digital channels.
						</p>
					</div>

				</div>
			</section>
			<section className="mt-16">
				<div className="max-w-6xl mx-auto px-4">
					<h2>Previous experience</h2>
					<div className="px-4 flex flex-col gap-4">
						<p>
							At <a href="https://www.mellcrest.com/" className="link-styled" target="_blank" rel="noopener noreferrer">Mellcrest</a>, I managed website content and worked with external agencies on SEO and web 
							development, helping improve search visibility, conversions, and revenue. I also built an 
							internal AI tool to improve product descriptions at scale.
						</p>
						<p>
							Earlier, during my placement year at Fade AV, I worked on analytics, content, and paid 
							search optimisation, using performance data to improve targeting and traffic quality.
						</p>
					</div>
				</div>
			</section>
			<section className="mt-16">
				<div className="max-w-6xl mx-auto px-4">
					<h2>Technical focus</h2>
					<div className="px-4 flex flex-col gap-4">
						<p>
							Alongside my day job, I build my own software and automation projects using Next.js, 
							React, Express, TypeScript, Python, SQL, and background workers.
						</p>
						<p>
							I enjoy understanding how systems connect, where friction sits, and how software can 
							improve the way people work. A lot of what I build is shaped by practical day-to-day 
							problems: repetitive tasks, messy data, and workflows that should be simpler than 
							they are.
						</p>
					</div>
				</div>
			</section>
		</div>
	)
}