import LinkCheckerDetail from "@/components/blocks/linkCheckerDetail";
import LinkCheckerDetailPages from '@/components/blocks/linkCheckerDetailPages';

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Job Detail Page",
  description: "Generated by me on my lonesome"
}

// unfortunately due to the fact that this is a super logic heavy page its literally all in a different component
export default function LinkCheckerDetailPage() {
	return (
		<div className="space-y-16">
		<section>
			<LinkCheckerDetail></LinkCheckerDetail>
		</section>
		<section>
            <LinkCheckerDetailPages></LinkCheckerDetailPages>
        </section>
		</div>

	)
}