import type { Metadata } from "next";
import ContactForm from "@/components/jobForms/contactForm";

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by me on my lonesome"
}

export default function Home() {
	return (
		<div className="space-y-16">
			<section className="mt-16">
				<div className="max-w-6xl mx-auto p-4 flex flex-col md:flex-row">
					<div className="flex-1">
						<h1>Contact</h1>
						<p>
							Feel free to get in touch about projects, questions or roles.
						</p>

					</div>
					<div className="flex-1"></div>
				</div>
			</section>
			<section>
				<div className="max-w-6xl mx-auto p-4 flex md:justify-center">
					<ContactForm></ContactForm>
				</div>
			</section>
		</div>
	)
}