import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Tools",
  description: "Generated by me on my lonesome"
}

export default function Home() {
	return (
		<div className="space-y-16">
			<section className="mt-16">
				<div className="max-w-6xl mx-auto p-4 flex flex-col md:flex-row">
					<div className="flex-1">
						<h1>All Tools</h1>
						<p>Let's actually automate work</p>
						<p className="px-4 mt-4">
							A collection of practical tools I&apos;ve built to automate repetitive work. 
							Each tool runs as a background job, and once complete you can inspect the 
							results in the app.
						</p>
					</div>
					<div className="flex-1"></div>
				</div>
			</section>
			<section>
				<div className="max-w-6xl mx-auto p-4 flex flex-wrap justify-center gap-4">
					<div className="card max-w-2xs flex flex-col gap-4">
						<div>
							<h3>Link Checker</h3>
							<p>Crawl a website and inspect its internal linking structure.</p>
						</div>
						<div className="flex flex-wrap justify-center gap-2">
							<Badge>Async</Badge>
							<Badge>Web crawler</Badge>
							<Badge variant="secondary">Login required</Badge>
						</div>
						<div>
							<p>How it works:</p>
							<ul className="custom-list">
								<li>Enter the website you want to scan</li>
								<li>The tool crawls the internal pages</li>
								<li>Review how pages link to one another once the job completes</li>
							</ul>
						</div>
	
						<Button asChild><Link href={"/tools/link-checker"}>Start scanning</Link></Button>
					</div>

					<div className="card max-w-2xs flex flex-col gap-4">
						<div>
							<h3>Under construction</h3>
							<p>Crawl Google Maps and extract all companies in a location</p>
						</div>
						<div className="flex flex-wrap justify-center gap-2">
							<Badge>Async</Badge>
							<Badge>Web crawler</Badge>
							<Badge variant="secondary">Login required</Badge>
						</div>
						<div>
							<p>How it works:</p>
							<ul className="custom-list">
								<li>Enter some coordinates</li>
								<li>The tool downloads data from Google Maps</li>
								<li>Review what companies are in your area once the scan is complete</li>
							</ul>
						</div>
	
						<Button className="mt-auto" disabled>Start scanning</Button>
					</div>

				</div>
			</section>
		</div>
	)
}